[build]
publish = "public"
command = "hugo --gc --minify"
baseUrl = "https://storj.io/blog"

[context.production.environment]
HUGO_VERSION = "0.58.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.58.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture"

[context.deploy-preview.environment]
HUGO_VERSION = "0.58.3"

[context.branch-deploy]
command = "hugo --gc --minify"

[context.branch-deploy.environment]
HUGO_VERSION = "รง"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/"
to = "https://tardigrade.io/blog/post/engineering/getting-from-petabytes-to-exabytes-the-road-ahead/"
status = 301
force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "deny"
    Strict-Transport-Security = "max-age=300; includeSubDomains"
    Content-Security-Policy = "default-src 'none'; script-src 'self' *.googleadservices.com *.google-analytics.com *.googleapis.com *.googletagmanager.com *.segment.com *.pingdom.net *.netlify.com unpkg.com *.customer.io *.abtasty.com; connect-src 'self' *.google.com *.segment.io *.google-analytics.com *.googleusercontent.com; img-src 'self' data: *.google-analytics.com *.customer.io *.doubleclick.net *.googletagmanager.com *.google.com; style-src 'self' *.googleapis.com *.cloudflare.com *.bootstrapcdn.com; base-uri 'self'; form-action 'self'; font-src 'self' *.gstatic.com *.cloudflare.com; child-src 'self' *.googletagmanager.com *.youtube.com;"
